         var data=    {
  "bag" : {
    "Ziploc" : {"name":"Ziploc",
      "img_name" : "ziploc.jpg",
      "location" : "recycling depot",
      "type" : "plastic",
      "img_recyle":"depot.jpg",
    },
    "chip" : {"name":"chip",
      "img_name" : "emptychipbag.jpg",
      "location" : "garbage",
      "type" : "plastic",
      "img_recyle":"garbage.jpg",
    },
    "paper_bag" : {"name":"paper_bag",
      "img_name" : "paperbag.jpg",
      "location" : "recycling bin",
      "type" : "paper",
      "img_recyle":"recycle_paper.jpg",
    },
    "shopping" : {"name":"shopping",
      "img_name" : "plasticgrocerybag.jpg",
      "location" : "grocery store",
      "location2" : "recycling depot",
      "type" : "plastic",
      "img_recyle":"reuse_plastic.jpg",
    }
  },
  "bottle" : {
    "glass_pop" : {"name":"glass_pop",
      "img_name" : "glasssoftdrink.jpg",
      "location2" : "blue bin",
      "location" : "recycling depot",
      "type" : "glass",
      "img_recyle":"depot.jpg",
    },
    "plastic_pop" : {"name":"plastic_pop",
      "img_name" : "plasticsoftdrink.jpg",
      "location" : "recycling depot",
      "type" : "plastic",
      "img_recyle":"depot.jpg",
    }
  },
  "box" : {
    "cardboard" : {"name":"cardboard",
      "img_name" : "cardboardbox.jpg",
      "location" : "recycling bin",
      "type" : "paper",
      "img_recyle":"recycle_bin.jpg",
    },
    "pizza" : {"name":"pizza",
      "img_name" : "pizzabox.jpg",
      "location" : "compost",
      "type" : "organics",
      "img_recyle":"compost.jpg",
    }
  }
}